name: Site QA
on:
  workflow_dispatch:
  push:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npx playwright install --with-deps

      - run: npm run urls

      - name: Scan pages
        run: npm run scan                 # use 'npm run scan:sample' for a fast ~60-page smoke
        continue-on-error: true           # keep job green even if pages have problems

      - name: Upload Playwright report
        if: always()                      # upload report even when scan step reports failures
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
